[project]
name = "pythonscripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.2.0",
    "astroquery>=0.4.11",
    "ffmpeg>=1.4",
    "galpy>=1.11.1",
    "imageio>=2.37.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "pvextractor>=0.4",
    "pywin32>=311",
    "requests>=2.34.0",
    "scipy>=1.17.0",
    "selenium>=4.41.0",
    "spectral-cube>=0.6.7",
]
